version: '2.2'
services:
  bionexo:
    build:
      context: ./
      dockerfile: Dockerfile
    image: bionexoapi
    ports:
      - '8080:8080'
    networks:
      - network1
    scale: 3

networks:
  network1: